
    <div class="col-xs-12">
        <div class="col-xs-12 linha">
            <h1><center>Gerenciador de Investimentos</center></h1>
        </div>
        
        <div class="col-xs-12">
        <div class="alert alert-warning alert-dismissable linha">
            <i class="fa fa-warning"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b>Promoção até dia 31/09/2014:</b> Adiquira o Gerenciador de Investimentos sem pagar mensalidade.
        </div>
        </div>

        <div class="col-xs-12 linha">
            <div class="col-xs-3"> </div>
            <div class="col-xs-3 align-right">
                <center>
                    <div class="price">R$497,00</div>
                    <small><italic>Sem mensalidade</italic></small><br>

                    <a href="https://www.hotmart.net.br/order/checkout/paydefault.html?order=P1605223P&amp;checkoutMode=0&amp;cid=613205">
                        <button type="submit" class="btn btn-warning btn-lg">Comprar Agora!</button></a>
                </center>
            </div>

            <div class="col-xs-3">
                <i class="icon-ok"></i>Acesso Ilimitado<br>
                <i class="icon-ok"></i>Sem taxas ocultas<br>
                <i class="icon-ok"></i>Suporte por telefone/email sem cobrança<br>
                <i class="icon-ok"></i>Sem contrato<br>
                <i class="icon-ok"></i>Sem burocracia<br>
            </div>

            <div class="col-xs-3"><br></div>
        </div>
        <div class="col-xs-12 linha">
            <div class="col-xs-3"> </div>
            <div class="box-security col-xs-6">
                <i class="icon-lock"></i>Todas as contas Finance-e são seguras, protegidas com senha e têm backup diário.
            </div>
            <div class="col-xs-3"> </div>
        </div>
        <div class="col-xs-12 linha">
            <ul class="ul">
                <li><a href="http://www.gerenciadordeinvestimentos#beneficios" target="blank">Benefícios</a></li>
                <li><a href="http://www.gerenciadordeinvestimentos#imagem" target="blank">Imagens</a></li>
                <li><a href="http://www.gerenciadordeinvestimentos#recursos" target="blank">Recursos</a></li>
                <li><a href="http://www.gerenciadordeinvestimentos#empresa" target="blank">A Empresa</a></li>
                <li><a href="http://www.gerenciadordeinvestimentos#oque"  target="blank">O que é?</a></li>
                <li><a href="http://www.emailmeform.com/builder/form/a80HdabbgE" target="_blank">Contato</a></li>
            </ul>
        </div>
        <div class="col-xs-12 linha">
            <div class="col-xs-3"> </div>
            <iframe width="560" height="315" src="//www.youtube.com/embed/vvAkttha_SE" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>