<?php
$this->Html->LoadCss('modulos/assine');
$linkanalise = $this->Html->getLink('pagamento/produto/show/' . COD_ANALISE);
$this->Html->LoadBowerComponent();
$this->Html->LoadAngular(array('angular/angular.min','angular-route/angular-route.min'));
$this->Html->LoadJs('produto/views/js/router.js');
?>

<ul class="dropdown" id="menu-dropdown">
        <li class="color1"> <a class="action_perm color1">Selecionar o produto</a> 
            <ul style="visibility: hidden; display: block;">
                <li class="color2"> <a href="#gerenciadordeinvestimentos" class="action_perm color2">Gerenciador de Investimentos</a></li>
                <li class="color2"> <a href="#analisedeinvestimentos" class="action_perm color2">Sistema para Análise de Ações</a></li>
            </ul> 
        </li>
    </ul>

<div ng-app="pag" ng-cloak="">
    <div ng-view></div>
</div>   
